name: Optimize Images

on:
  push:
    branches:
      - main
    paths:
      - 'images/**'
  pull_request:
    paths:
      - 'images/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  optimize:
    name: Optimize Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compress Images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
          ignorePaths: 'node_modules/**,dist/**,slides/**'
          jpegQuality: '85'
          jpegProgressive: true
          pngQuality: '85'
          webpQuality: '85'
